spring:
  mvc:
    view:
      suffix: .html
jwt:
  token:
    secret-key: "aaaaagaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" # >= 256bits
    access-expired-ms: 31540000000 # 24 * 3600000 = 24 hours
